name: UNSERtaube

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: UNSERtaube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    image: unserprojekt/taube:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: localhost
    network_mode: host
    volumes:
      - ./taube_rsa:/credentials/taube_rsa:ro
  
  forwarder:
    image: unserprojekt/forwarder:latest
    build:
      context: ./winhacks
      dockerfile: Dockerfile
    
    restart: always
    ports:
      - "8443:8443"

volumes:
  postgres_data: